### ISSUE TITLE
Server crash on launch

### ISSUE THREAD

**Issue by KingQuarter** [thqby/vscode-autohotkey2-lsp#129]
# Steps
Install version 1.4.7 of the extension.
# Result
![image](https://user-images.githubusercontent.com/92368853/181236511-1ac22e1d-b96c-43ea-8f81-ea348212b51e.png)
### First, the contents of server.js are spat out:
(I won't paste the whole thing as it's too long; hence, the ellipses at the end.)
```
c:\Users\KingQuarter\.vscode\extensions\thqby.vscode-autohotkey2-lsp-1.4.7\server\dist\server.js:1
(()=>{"use strict";var e={6169:(e,t,n)=>{Object.defineProperty(t,"__esModule",{value:!0}),t.checksamenameerr=t.samenameerr=t.formatMarkdowndetail=t....
```
### Then:
```
TypeError: Cannot read properties of undefined (reading 'scriptdir')
    at O.update_relevance (c:\Users\KingQuarter\.vscode\extensions\thqby.vscode-autohotkey2-lsp-1.4.7\server\dist\server.js:1:101423)
    at c:\Users\KingQuarter\.vscode\extensions\thqby.vscode-autohotkey2-lsp-1.4.7\server\dist\server.js:1:350134
    at o.invoke (c:\Users\KingQuarter\.vscode\extensions\thqby.vscode-autohotkey2-lsp-1.4.7\server\dist\server.js:1:220430)
    at r.fire (c:\Users\KingQuarter\.vscode\extensions\thqby.vscode-autohotkey2-lsp-1.4.7\server\dist\server.js:1:221191)
    at c:\Users\KingQuarter\.vscode\extensions\thqby.vscode-autohotkey2-lsp-1.4.7\server\dist\server.js:1:305754
    at c:\Users\KingQuarter\.vscode\extensions\thqby.vscode-autohotkey2-lsp-1.4.7\server\dist\server.js:1:211916
    at c:\Users\KingQuarter\.vscode\extensions\thqby.vscode-autohotkey2-lsp-1.4.7\server\dist\server.js:1:212134
    at Immediate.<anonymous> (c:\Users\KingQuarter\.vscode\extensions\thqby.vscode-autohotkey2-lsp-1.4.7\server\dist\server.js:1:213682)
    at processImmediate (node:internal/timers:464:21)
[Error - 6:00:01 PM] Connection to server got closed. Server will not be restarted.
```
### The following repeats 3 times:
```
[Error - 6:00:01 PM] Request textDocument/documentSymbol failed.
Error: Connection got disposed.
	at Object.dispose (c:\Users\KingQuarter\.vscode\extensions\thqby.vscode-autohotkey2-lsp-1.4.7\client\dist\extension.js:1:35805)
	at Object.dispose (c:\Users\KingQuarter\.vscode\extensions\thqby.vscode-autohotkey2-lsp-1.4.7\client\dist\extension.js:1:115896)
	at w.handleConnectionClosed (c:\Users\KingQuarter\.vscode\extensions\thqby.vscode-autohotkey2-lsp-1.4.7\client\dist\extension.js:1:116109)
	at w.handleConnectionClosed (c:\Users\KingQuarter\.vscode\extensions\thqby.vscode-autohotkey2-lsp-1.4.7\client\dist\extension.js:1:176473)
	at t (c:\Users\KingQuarter\.vscode\extensions\thqby.vscode-autohotkey2-lsp-1.4.7\client\dist\extension.js:1:114198)
	at r.invoke (c:\Users\KingQuarter\.vscode\extensions\thqby.vscode-autohotkey2-lsp-1.4.7\client\dist\extension.js:1:37418)
	at o.fire (c:\Users\KingQuarter\.vscode\extensions\thqby.vscode-autohotkey2-lsp-1.4.7\client\dist\extension.js:1:38179)
	at Y (c:\Users\KingQuarter\.vscode\extensions\thqby.vscode-autohotkey2-lsp-1.4.7\client\dist\extension.js:1:25063)
	at r.invoke (c:\Users\KingQuarter\.vscode\extensions\thqby.vscode-autohotkey2-lsp-1.4.7\client\dist\extension.js:1:37418)
	at o.fire (c:\Users\KingQuarter\.vscode\extensions\thqby.vscode-autohotkey2-lsp-1.4.7\client\dist\extension.js:1:38179)
	at d.fireClose (c:\Users\KingQuarter\.vscode\extensions\thqby.vscode-autohotkey2-lsp-1.4.7\client\dist\extension.js:1:46060)
	at ChildProcess.<anonymous> (c:\Users\KingQuarter\.vscode\extensions\thqby.vscode-autohotkey2-lsp-1.4.7\client\dist\extension.js:1:57026)
	at ChildProcess.emit (node:events:402:35)
	at maybeClose (node:internal/child_process:1064:16)
	at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
```
# Notes
- In the output above, I have changed the name of my user profile folder from my real-life name to my GitHub username, KingQuarter.
- Issue doesn't happen on version 1.4.6,
- happens regardless if restricted mode is on or off,
- happens on VS Code reload,
- happens on closing VS Code and opening it again,
- happens on extension reinstall,
- happens on device restart, and
- happens on VS Code reinstall.
# Specifics
AutoHotkey2 version: 1.4.7
VS Code Version: 1.69.2 (user setup)
Commit: 3b889b090b5ad5793f524b5d1d39fda662b96a2a
Date: 2022-07-18T16:12:52.460Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.22000

**Comment by KingQuarter** [comment]
Fixed by fb1e366
