### ISSUE TITLE
Extension crashes when opening any project

### ISSUE THREAD

**Issue by Descolada** [thqby/vscode-autohotkey2-lsp#199]
I've had the same problem before as well but it went away by itself. Now I am unable to open VSCode without the extension crashing with the following output:
```
TypeError: r.get is not a function
    at c:\Users\user\.vscode\extensions\thqby.vscode-autohotkey2-lsp-1.6.6\server\dist\server.js:1:361860
    at P.e.uri.match.parseScript (c:\Users\user\.vscode\extensions\thqby.vscode-autohotkey2-lsp-1.6.6\server\dist\server.js:1:96630)
    at t.parseWorkspaceFolders (c:\Users\user\.vscode\extensions\thqby.vscode-autohotkey2-lsp-1.6.6\server\dist\server.js:1:155094)
    at c:\Users\user\.vscode\extensions\thqby.vscode-autohotkey2-lsp-1.6.6\server\dist\server.js:1:364667
    at c:\Users\user\.vscode\extensions\thqby.vscode-autohotkey2-lsp-1.6.6\server\dist\server.js:1:226961
    at c:\Users\user\.vscode\extensions\thqby.vscode-autohotkey2-lsp-1.6.6\server\dist\server.js:1:227179
    at Immediate.<anonymous> (c:\Users\user\.vscode\extensions\thqby.vscode-autohotkey2-lsp-1.6.6\server\dist\server.js:1:228727)
    at process.processImmediate (node:internal/timers:466:21)
[Error - 18:54:09] Connection to server got closed. Server will not be restarted.
[Error - 18:54:09] Request textDocument/documentSymbol failed.
Error: Connection got disposed.
	at Object.dispose (c:\Users\user\.vscode\extensions\thqby.vscode-autohotkey2-lsp-1.6.6\client\dist\extension.js:1:35805)
	at Object.dispose (c:\Users\user\.vscode\extensions\thqby.vscode-autohotkey2-lsp-1.6.6\client\dist\extension.js:1:115896)
	at w.handleConnectionClosed (c:\Users\user\.vscode\extensions\thqby.vscode-autohotkey2-lsp-1.6.6\client\dist\extension.js:1:116109)
	at w.handleConnectionClosed (c:\Users\user\.vscode\extensions\thqby.vscode-autohotkey2-lsp-1.6.6\client\dist\extension.js:1:176473)
	at t (c:\Users\user\.vscode\extensions\thqby.vscode-autohotkey2-lsp-1.6.6\client\dist\extension.js:1:114198)
	at r.invoke (c:\Users\user\.vscode\extensions\thqby.vscode-autohotkey2-lsp-1.6.6\client\dist\extension.js:1:37418)
	at o.fire (c:\Users\user\.vscode\extensions\thqby.vscode-autohotkey2-lsp-1.6.6\client\dist\extension.js:1:38179)
	at Y (c:\Users\user\.vscode\extensions\thqby.vscode-autohotkey2-lsp-1.6.6\client\dist\extension.js:1:25063)
	at r.invoke (c:\Users\user\.vscode\extensions\thqby.vscode-autohotkey2-lsp-1.6.6\client\dist\extension.js:1:37418)
	at o.fire (c:\Users\user\.vscode\extensions\thqby.vscode-autohotkey2-lsp-1.6.6\client\dist\extension.js:1:38179)
	at d.fireClose (c:\Users\user\.vscode\extensions\thqby.vscode-autohotkey2-lsp-1.6.6\client\dist\extension.js:1:46060)
	at ChildProcess.<anonymous> (c:\Users\user\.vscode\extensions\thqby.vscode-autohotkey2-lsp-1.6.6\client\dist\extension.js:1:57026)
	at ChildProcess.emit (node:events:538:35)
	at maybeClose (node:internal/child_process:1092:16)
	at ChildProcess._handle.onexit (node:internal/child_process:302:5)
[Error - 18:54:09] Request textDocument/codeAction failed.
Error: Connection got disposed.
	at Object.dispose (c:\Users\user\.vscode\extensions\thqby.vscode-autohotkey2-lsp-1.6.6\client\dist\extension.js:1:35805)
	at Object.dispose (c:\Users\user\.vscode\extensions\thqby.vscode-autohotkey2-lsp-1.6.6\client\dist\extension.js:1:115896)
	at w.handleConnectionClosed (c:\Users\user\.vscode\extensions\thqby.vscode-autohotkey2-lsp-1.6.6\client\dist\extension.js:1:116109)
	at w.handleConnectionClosed (c:\Users\user\.vscode\extensions\thqby.vscode-autohotkey2-lsp-1.6.6\client\dist\extension.js:1:176473)
	at t (c:\Users\user\.vscode\extensions\thqby.vscode-autohotkey2-lsp-1.6.6\client\dist\extension.js:1:114198)
	at r.invoke (c:\Users\user\.vscode\extensions\thqby.vscode-autohotkey2-lsp-1.6.6\client\dist\extension.js:1:37418)
	at o.fire (c:\Users\user\.vscode\extensions\thqby.vscode-autohotkey2-lsp-1.6.6\client\dist\extension.js:1:38179)
	at Y (c:\Users\user\.vscode\extensions\thqby.vscode-autohotkey2-lsp-1.6.6\client\dist\extension.js:1:25063)
	at r.invoke (c:\Users\user\.vscode\extensions\thqby.vscode-autohotkey2-lsp-1.6.6\client\dist\extension.js:1:37418)
	at o.fire (c:\Users\user\.vscode\extensions\thqby.vscode-autohotkey2-lsp-1.6.6\client\dist\extension.js:1:38179)
	at d.fireClose (c:\Users\user\.vscode\extensions\thqby.vscode-autohotkey2-lsp-1.6.6\client\dist\extension.js:1:46060)
	at ChildProcess.<anonymous> (c:\Users\user\.vscode\extensions\thqby.vscode-autohotkey2-lsp-1.6.6\client\dist\extension.js:1:57026)
	at ChildProcess.emit (node:events:538:35)
	at maybeClose (node:internal/child_process:1092:16)
	at ChildProcess._handle.onexit (node:internal/child_process:302:5)
[Error - 18:54:09] Request textDocument/colorPresentation failed.
Error: Connection got disposed.
	at Object.dispose (c:\Users\user\.vscode\extensions\thqby.vscode-autohotkey2-lsp-1.6.6\client\dist\extension.js:1:35805)
	at Object.dispose (c:\Users\user\.vscode\extensions\thqby.vscode-autohotkey2-lsp-1.6.6\client\dist\extension.js:1:115896)
	at w.handleConnectionClosed (c:\Users\user\.vscode\extensions\thqby.vscode-autohotkey2-lsp-1.6.6\client\dist\extension.js:1:116109)
	at w.handleConnectionClosed (c:\Users\user\.vscode\extensions\thqby.vscode-autohotkey2-lsp-1.6.6\client\dist\extension.js:1:176473)
	at t (c:\Users\user\.vscode\extensions\thqby.vscode-autohotkey2-lsp-1.6.6\client\dist\extension.js:1:114198)
	at r.invoke (c:\Users\user\.vscode\extensions\thqby.vscode-autohotkey2-lsp-1.6.6\client\dist\extension.js:1:37418)
	at o.fire (c:\Users\user\.vscode\extensions\thqby.vscode-autohotkey2-lsp-1.6.6\client\dist\extension.js:1:38179)
	at Y (c:\Users\user\.vscode\extensions\thqby.vscode-autohotkey2-lsp-1.6.6\client\dist\extension.js:1:25063)
	at r.invoke (c:\Users\user\.vscode\extensions\thqby.vscode-autohotkey2-lsp-1.6.6\client\dist\extension.js:1:37418)
	at o.fire (c:\Users\user\.vscode\extensions\thqby.vscode-autohotkey2-lsp-1.6.6\client\dist\extension.js:1:38179)
	at d.fireClose (c:\Users\user\.vscode\extensions\thqby.vscode-autohotkey2-lsp-1.6.6\client\dist\extension.js:1:46060)
	at ChildProcess.<anonymous> (c:\Users\user\.vscode\extensions\thqby.vscode-autohotkey2-lsp-1.6.6\client\dist\extension.js:1:57026)
	at ChildProcess.emit (node:events:538:35)
	at maybeClose (node:internal/child_process:1092:16)
	at ChildProcess._handle.onexit (node:internal/child_process:302:5)
```

Highlighting still works, but no autosuggestions/Intellisense. I've tried reinstalling the extension multiple times and have tried deleting the config files.

**Comment by gwenreynolds94** [comment]
Happened to me as well. It's the most recent update. The previous version works fine for me so I'm using that for the time being.

**Comment by Axlefublr** [comment]
Here to ~~second~~ third this. Thought it was because of me switching to the neovim extension after the usual vim extension but I checked and it's not the issue. Glad to see it's not, in a weird sense.

**Comment by Axlefublr** [comment]
Here's how to downgrade:

![image](https://user-images.githubusercontent.com/101342105/193696553-b436fc75-fe78-4d44-a1e9-8cc4de8fd9a8.png)
![image](https://user-images.githubusercontent.com/101342105/193696572-36de9602-af46-4dd3-bb6d-9ae64dd346eb.png)
![image](https://user-images.githubusercontent.com/101342105/193696598-c3c4ae77-0555-4de4-b607-8ef9c92d2e76.png)
![image](https://user-images.githubusercontent.com/101342105/193696619-afcb4699-2453-40b9-9679-6de8664def64.png)
![image](https://user-images.githubusercontent.com/101342105/193696624-40fe6464-d28c-48f3-80f3-dffb23ce1447.png)

Did so and everything works again 😼

**Comment by thqby** [comment]
![image](https://user-images.githubusercontent.com/28240311/193710204-71c9431d-9f8b-408e-8897-55e6a2fd5bbb.png)

You can switch versions directly in vscode.

**Comment by thqby** [comment]
@Descolada @Axlefublr @gwenreynolds94 
What are your versions of NodeJS and VScode?
Help - About 
![image](https://user-images.githubusercontent.com/28240311/193713644-3e72edb4-6af6-499e-9511-7987773d935e.png)

**Comment by thqby** [comment]
Is it the latest version of vscode?
I can't repeat the issue.

**Comment by Descolada** [comment]
@thqby running latest VSCode 1.71.2 on Windows 10 21H2 (OS Build 19044.2006). I'll try to reproduce this issue later, but in the meanwhile downgrading to 1.6.5 fixed the issue.

**Comment by thqby** [comment]
1.6.7 has been released.

**Comment by gwenreynolds94** [comment]
1.6.7 works perfectly for me

**Comment by Axlefublr** [comment]
Same for me, 1.6.7 doesn't break

**Comment by Descolada** [comment]
@thqby yep, fixed now, thank you :)
