### ISSUE TITLE
[Bug] LSP server crashes in Neovim

### ISSUE THREAD

**Issue by pidgeon777** [thqby/vscode-autohotkey2-lsp#207]
In Neovim v0.8, LSP server crash with this error few seconds after opening a AHK file:

```
TypeError: Cannot read properties of null (reading 'InterpreterPath')
    at Ee (C:\\Work\\Projects\\Repositories\\GitHub\\thqby\\vscode-autohotkey2-lsp\\server\\dist\\server.js:1:162975)
    at async C:\\Work\\Projects\\Repositories\\GitHub\\thqby\\vscode-autohotkey2-lsp\\server\\dist\\server.js:1:131695
    Node.js v17.9.1
    "
```

My config:

```lua
local M = {}

M.config = function()
  local lsp_configs = require "lspconfig.configs"
  local cmd
  cmd = {
    "node",
    "C:/Work/Projects/Repositories/GitHub/thqby/vscode-autohotkey2-lsp/server/dist/server.js",
    "--stdio",
    "--node-ipc"
  }

  lsp_configs.ahk2_lsp = {
    default_config = {
      cmd = cmd,
      filetypes = { "autohotkey", "autohotkey2" },
      root_dir = function(fname)
        local util = require "lspconfig.util"
        local root_files = {
          "ahk2_lsp.json",
        }
        return util.root_pattern(unpack(root_files))(fname) or util.root_pattern ".git"(fname) or util.path.dirname(fname)
      end,
      single_file_support = true,
      cmd_env = {
        AHK2_LS_CONFIG = '{"locale":"en-us"}',
      },
      settings = {
        AutoHotKey2 = {
          InterpreterPath = 'C:/Program Files/Autohotkey/AutoHotkey.exe',
          AutoLibInclude = 0,
        },
      },

      docs = {
        description = [[
https://github.com/thqby/vscode-autohotkey2-lsp

Autohotkey2 Language Support 

Download and unpack thqby.vscode-autohotkey2-LSP plugin 
from vscode marketplace, https://marketplace.visualstudio.com/items?itemName=thqby.vscode-autohotkey2-lsp
cmd = {'node', 'extension/server/dist/server.js', '--stdio'}
]],
        default_config = {
          root_dir = [[util.root_pattern(unpack(root_files))(fname)]],
        },
      },
    },
  }

  local status_ok, lsp = pcall(require, "lspconfig")
  if not status_ok then
    return
  end

  if lsp.ahk2_lsp.setup then
    lsp.ahk2_lsp.setup {
      on_attach = function(client, bufnr)
      end,
      on_init = require("lvim.lsp").common_on_init,
      capabilities = require("lvim.lsp").common_capabilities(),
    }
  end
end
return M
```

**Comment by thqby** [comment]
Which version?

https://github.com/thqby/vscode-autohotkey2-lsp#vim-and-neovim
Pass the initial Settings using `initializationOptions`

**Comment by pidgeon777** [comment]
I'm using the 1.7.0 AHK LSP server version, but how should I pass that `initializationOptions` setting in the LUA config I posted above?

**Comment by thqby** [comment]
https://github.com/neovim/nvim-lspconfig/wiki/Understanding-setup-%7B%7D#init_options
```
init_options = {

}
```

**Comment by pidgeon777** [comment]
This is now my setup:

```lua
local M = {}

M.config = function()
  local lsp_configs = require "lspconfig.configs"

  local cmd
  cmd = {
    "node",
    "C:/Work/Projects/Repositories/GitHub/thqby/vscode-autohotkey2-lsp/server/dist/server.js",
    "--stdio"
  }

  lsp_configs.ahk2_lsp = {
    default_config = {
      cmd = cmd,
      filetypes = { "autohotkey", "autohotkey2" },
      root_dir = function(fname)
        local util = require "lspconfig.util"
        local root_files = {
          "ahk2_lsp.json",
        }
        return util.root_pattern(unpack(root_files))(fname) or util.root_pattern ".git"(fname) or util.path.dirname(fname)
      end,
      single_file_support = true,
      cmd_env = {
        AHK2_LS_CONFIG = '{"locale":"en-us"}',
      },
      settings = {},
      init_options = {
        AutoHotKey2 = {
          InterpreterPath = 'C:/Program Files/Autohotkey/AutoHotkey.exe',
          AutoLibInclude = 0,
        },
      },

      docs = {
        description = [[
https://github.com/thqby/vscode-autohotkey2-lsp

Autohotkey2 Language Support 

Download and unpack thqby.vscode-autohotkey2-LSP plugin 
from vscode marketplace, https://marketplace.visualstudio.com/items?itemName=thqby.vscode-autohotkey2-lsp
cmd = {'node', 'extension/server/dist/server.js', '--stdio'}
]],
        default_config = {
          root_dir = [[util.root_pattern(unpack(root_files))(fname)]],
        },
      },
    },
  }

  local status_ok, lsp = pcall(require, "lspconfig")
  if not status_ok then
    return
  end

  if lsp.ahk2_lsp.setup then
    lsp.ahk2_lsp.setup {
      on_attach = function(client, bufnr)
        require('navigator.lspclient.attach').on_attach(client, bufnr)
      end,
      on_init = require("lvim.lsp").common_on_init,
      capabilities = require("lvim.lsp").common_capabilities(),
    }
  end
end
return M
```

Still, this error is produced:

```
TypeError: Cannot read properties of null (reading 'InterpreterPath')
    at Ee (C:\\Work\\Projects\\Repositories\\GitHub\\thqby\\vscode-autohotkey2-lsp\\server\\dist\\server.js:1:162975)
    at async C:\\Work\\Projects\\Repositories\\GitHub\\thqby\\vscode-autohotkey2-lsp\\server\\dist\\server.js:1:131695
    Node.js v17.9.1
    "
```

**Comment by thqby** [comment]
```
init_options = {
    InterpreterPath = 'C:/Program Files/Autohotkey/AutoHotkey.exe',
    AutoLibInclude = 0,
}
```
??

```
init_options = {
        AutoHotkey2 = {
          InterpreterPath = 'C:/Program Files/Autohotkey/AutoHotkey.exe',
          AutoLibInclude = 0,
        },
      }
```
??

**Comment by pidgeon777** [comment]
Tried both, unfortunately the server still crashes.

I attach the LSP server log for this configuration:

```lua
init_options = {
        AutoHotkey2 = {
          locale = "en-us",
          InterpreterPath = 'C:/Program Files/Autohotkey/AutoHotkey.exe',
          AutoLibInclude = 0,
        },
      }
```

Neovim LSP log file:

https://gist.github.com/pidgeon777/61fdb037a89eef6faea9d4af63a7c505

Server version is:

![image](https://user-images.githubusercontent.com/13739892/198879813-5698812a-b535-4625-abd2-caaed59c3335.png)

**Comment by thqby** [comment]
```
init_options = {
        configuration = {
          locale = "en-us",
          InterpreterPath = 'C:/Program Files/Autohotkey/AutoHotkey.exe',
          AutoLibInclude = 0,
        },
      },
```
??

**Comment by thqby** [comment]
![image](https://user-images.githubusercontent.com/28240311/198885591-2944df85-8c66-4428-ac5e-e44c9bb736d6.png)

**Comment by thqby** [comment]
Have you solved this issue?

**Comment by pidgeon777** [comment]
Unfortunately not.

It is like the Neovim LSP client is not sending the `init_options` table to the server, very strange.

I've to investigate this.

**Comment by thqby** [comment]
Can't the above configuration work either?

**Comment by pidgeon777** [comment]
I tried the config you attached in your latest post right above, and here is the result:

https://gist.github.com/pidgeon777/389bff73b6950203d04e0de4807b82ca

It seems like the Neovim client is sending the `InterpreterPath` information to the AHK LSP server, but somehow that field is not identified by the server itself. Particularly:

```
\r\n\r\nTypeError: Cannot read properties of null (reading 'InterpreterPath')\r\n    at Ee (C:\\Work\\Projects\\Repositories\\GitHub\\thqby\\vscode-autohotkey2-lsp\\server\\dist\\server.js:1:162975)\r\n    at async C:\\Work\\Projects\\Repositories\\GitHub\\thqby\\vscode-autohotkey2-lsp\\server\\dist\\server.js:1:131695\r\n\r\nNode.js v17.9.
```

I'm currently using the LSP server from this commit of your repository:

https://github.com/thqby/vscode-autohotkey2-lsp/commit/69262878d8747f166c96010b652462568d0702a1

**Comment by pidgeon777** [comment]
I feel rather stupid.

For somewhat reason, my `server.js` file was not the latest one available from your repository.

It was a version dating back to July 2021. Ugh.

Now I re-generated the `server.js` file by doing this:

1. install nodejs
2. cd vscode-autohotkey2-lsp
3. npm install
4. npm install -g webpack
5. npm install -g webpack-cli
6. npm run vscode:prepublish

And it finally ran.

**Comment by thqby** [comment]
> I'm currently using the LSP server from this commit of your repository:
> [6926287](https://github.com/thqby/vscode-autohotkey2-lsp/commit/69262878d8747f166c96010b652462568d0702a1)

The source code is different from the actual js file. The source code I unpacked from the vscode market does not match the error location.

This is not the most important. The above configuration works normally here.
My nvim version is also 0.8, but nodejs version is v16.14.2, I don't think this will lead to this issue.
**I don't know if there are different versions of nvim's lspconfig.**

Or you can use the configuration of this [repository](https://github.com/ayamir/nvimdots) to redeploy an environment. After installing the nvim plug-in, I only modified this files `C:\Users\<username>\AppData\Local\nvim\lua\modules\completion\lsp.lua` 
and `C:\Users\<username>\AppData\Local\nvim\lua\core\settings.lua`.

**Comment by thqby** [comment]
`server.js` can also be downloaded from the server branch.

**Comment by pidgeon777** [comment]
I'll try the new config and do some tests.
