### ISSUE TITLE
Request textDocument/documentSymbol failed.

### ISSUE THREAD

**Issue by samfisherirl** [thqby/vscode-autohotkey2-lsp#481]
https://github.com/thqby/vscode-autohotkey2-lsp/assets/98753696/07d79b22-84cc-47ec-bfdc-bb47784a43ed

this issue has been persistent, happy to provide details on logs and use an incog account without other extensions. 

Turning off notifications has not allowed me to ignore this. Its been an issue for a few months and I've tweaked the settings. 

The extension is set to suppress or ignore, and I show the settings in the video for vscode. 

This issue doesnt always happen but consistently an issue.

**Comment by TWT233** [comment]
same here, and seems this error leads to a formatting that removes all my trailing lines:

after:
![image](https://github.com/thqby/vscode-autohotkey2-lsp/assets/11287700/128434a2-571a-4d87-800f-ab4015117df2)

before:
![image](https://github.com/thqby/vscode-autohotkey2-lsp/assets/11287700/b75d804e-e025-41c7-8b8a-8cb14bda6c48)

**Comment by TWT233** [comment]
I downgrade the plugin to 2.3.2 and it's fine now
![image](https://github.com/thqby/vscode-autohotkey2-lsp/assets/11287700/1ea1b4b5-cd90-4a6c-be7f-034df0c52f14)

**Comment by thqby** [comment]
@samfisherirl 
The Settings do not affect this error, please provide an error message in the ahk2 output or developer tools(Ctrl+Shift+I)

**Comment by samfisherirl** [comment]
> @samfisherirl The Settings do not affect this error, please provide an error message displayed in the ahk2 output or developer tools(Ctrl+Shift+I)

```
[Error - 2:40:24 AM] Request textDocument/documentSymbol failed.
Error: name must not be falsy
	at h.validate (c:\Users\dower\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:148:16844)
	at new h (c:\Users\dower\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:148:17082)
	at z (c:\Users\dower\.vscode\extensions\thqby.vscode-autohotkey2-lsp-2.3.3\client\dist\extension.js:1:212855)
	at c (c:\Users\dower\.vscode\extensions\thqby.vscode-autohotkey2-lsp-2.3.3\client\dist\extension.js:1:251455)
	at t.map (c:\Users\dower\.vscode\extensions\thqby.vscode-autohotkey2-lsp-2.3.3\client\dist\extension.js:1:251541)
	at Object.asSymbolInformations (c:\Users\dower\.vscode\extensions\thqby.vscode-autohotkey2-lsp-2.3.3\client\dist\extension.js:1:220962)
	at i (c:\Users\dower\.vscode\extensions\thqby.vscode-autohotkey2-lsp-2.3.3\client\dist\extension.js:1:157352)
	at async s.provideDocumentSymbols (c:\Users\dower\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:85454)
[Error - 2:40:25 AM] Request textDocument/documentSymbol failed.
Error: name must not be falsy
	at h.validate (c:\Users\dower\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:148:16844)
	at new h (c:\Users\dower\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:148:17082)
	at z (c:\Users\dower\.vscode\extensions\thqby.vscode-autohotkey2-lsp-2.3.3\client\dist\extension.js:1:212855)
	at c (c:\Users\dower\.vscode\extensions\thqby.vscode-autohotkey2-lsp-2.3.3\client\dist\extension.js:1:251455)
	at t.map (c:\Users\dower\.vscode\extensions\thqby.vscode-autohotkey2-lsp-2.3.3\client\dist\extension.js:1:251541)
	at Object.asSymbolInformations (c:\Users\dower\.vscode\extensions\thqby.vscode-autohotkey2-lsp-2.3.3\client\dist\extension.js:1:220962)
	at i (c:\Users\dower\.vscode\extensions\thqby.vscode-autohotkey2-lsp-2.3.3\client\dist\extension.js:1:157352)
	at async s.provideDocumentSymbols (c:\Users\dower\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:85454)
[Error - 2:40:29 AM] Request textDocument/documentSymbol failed.
Error: name must not be falsy
    at Function.validate (c:\Users\dower\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:148:16844)
    at new h (c:\Users\dower\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:148:17082)
    at z (c:\Users\dower\.vscode\extensions\thqby.vscode-autohotkey2-lsp-2.3.3\client\dist\extension.js:1:212855)
    at c (c:\Users\dower\.vscode\extensions\thqby.vscode-autohotkey2-lsp-2.3.3\client\dist\extension.js:1:251455)
    at Object.t.map (c:\Users\dower\.vscode\extensions\thqby.vscode-autohotkey2-lsp-2.3.3\client\dist\extension.js:1:251541)
    at Object.asSymbolInformations (c:\Users\dower\.vscode\extensions\thqby.vscode-autohotkey2-lsp-2.3.3\client\dist\extension.js:1:220962)
    at i (c:\Users\dower\.vscode\extensions\thqby.vscode-autohotkey2-lsp-2.3.3\client\dist\extension.js:1:157352)
    at s.provideDocumentSymbols (c:\Users\dower\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:85454)

```

**Comment by samfisherirl** [comment]
> @samfisherirl 
> The Settings do not affect this error, please provide an error message displayed in the ahk2 output or developer tools(Ctrl+Shift+I)

Underlines my issue that I cannot suppress errors. There's a built in common feature to turn off notifications but many releases seem to throw outside of that.

**Comment by thqby** [comment]
This notification is thrown by vscode and I'm not sure if I can turn it off.

**Comment by TJGinis** [comment]
[Error - 2:03:45 PM] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Cannot access 'c' before initialization
  Code: -32603

**Comment by TJGinis** [comment]
> I downgrade the plugin to 2.3.2 and it's fine now ![image](https://private-user-images.githubusercontent.com/11287700/307489998-1ea1b4b5-cd90-4a6c-be7f-034df0c52f14.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg4MDEwODcsIm5iZiI6MTcwODgwMDc4NywicGF0aCI6Ii8xMTI4NzcwMC8zMDc0ODk5OTgtMWVhMWI0YjUtY2Q5MC00YTZjLWJlN2YtMDM0ZGYwYzUyZjE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI0VDE4NTMwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5ZjRjYjEwOTRkY2IyODE3ODAzYzVmOWMxMWI4MTRmYmFiZjM3MGU5YzVjZTJjNGY1MzRhN2VjMDQ5YjNjOTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.T1o_gj8CVlncUT9RqvvlHH9bGlmH1UOZ2OMicsPTbJw)

Downgrading to 2.3.2 seems to have fixed it for me as well.
