### ISSUE TITLE
Document Symbol Failed

### ISSUE THREAD

**Issue by RaptorX** [thqby/vscode-autohotkey2-lsp#482]
Type: <b>Bug</b>

Newest version has this issue again, similar to #333 but seems caused by a different symbol:

```
[Error - 9:34:47 AM] Request textDocument/documentSymbol failed.
Error: name must not be falsy
    at Function.validate (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:148:16844)
    at new h (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:148:17082)
    at z (c:\Users\RaptorX\.vscode\extensions\thqby.vscode-autohotkey2-lsp-2.3.3\client\dist\extension.js:1:212855)
    at c (c:\Users\RaptorX\.vscode\extensions\thqby.vscode-autohotkey2-lsp-2.3.3\client\dist\extension.js:1:251455)
    at Object.t.map (c:\Users\RaptorX\.vscode\extensions\thqby.vscode-autohotkey2-lsp-2.3.3\client\dist\extension.js:1:251541)
    at Object.asSymbolInformations (c:\Users\RaptorX\.vscode\extensions\thqby.vscode-autohotkey2-lsp-2.3.3\client\dist\extension.js:1:220962)
    at i (c:\Users\RaptorX\.vscode\extensions\thqby.vscode-autohotkey2-lsp-2.3.3\client\dist\extension.js:1:157352)
    at s.provideDocumentSymbols (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:85454)
[Error - 9:35:01 AM] Request textDocument/documentSymbol failed.
```

---

Extension version: 2.3.3
VS Code version: Code 1.86.2 (903b1e9d8990623e3d7da1df3d33db3e42d80eda, 2024-02-13T19:40:56.878Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz (4 x 3198)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.88GB (21.71GB free)|
|Process Argv|S:\\Clip_Share\\V2\\Dev\\ClipShareV2 - WIP.ahk --crash-reporter-id 3e042e59-cb22-4371-968a-6f3e35abe666|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
pydisww2:30959801
d34g3935:30971562
edj9j583:30969295
fegfb526:30961430
7j2b6412:30969109
ccp1r6:30958156

```

</details>

**Comment by thqby** [comment]
Duplicate with #481
