### ISSUE TITLE
crashed: ReferenceError: self is not defined

### ISSUE THREAD

**Issue by FuPeiJiang** [thqby/vscode-autohotkey2-lsp#53]
Version 1.1.0

OUTPUT tab:
![image](https://user-images.githubusercontent.com/42662615/139566509-9e5a96c4-570b-4761-8c70-43b326f8fa92.png)

c:\Users\User\.vscode\extensions\thqby.vscode-autohotkey2-lsp-1.1.0\server\dist\server.js:1
```
ReferenceError: self is not defined
    at Object.4603 (c:\Users\User\.vscode\extensions\thqby.vscode-autohotkey2-lsp-1.1.0\server\dist\server.js:1:162374)
    at n (c:\Users\User\.vscode\extensions\thqby.vscode-autohotkey2-lsp-1.1.0\server\dist\server.js:1:319822)
    at c:\Users\User\.vscode\extensions\thqby.vscode-autohotkey2-lsp-1.1.0\server\dist\server.js:1:320189
    at Object.<anonymous> (c:\Users\User\.vscode\extensions\thqby.vscode-autohotkey2-lsp-1.1.0\server\dist\server.js:1:320216)
    at Module._compile (internal/modules/cjs/loader.js:1125:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1155:10)
    at Module.load (internal/modules/cjs/loader.js:982:32)
    at Module._load (internal/modules/cjs/loader.js:823:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
[Error - 11:43:55 p.m.] Connection to server got closed. Server will not be restarted.
```

**Comment by thqby** [comment]
A mistake, the fixed version did not upload successfully.
