### ISSUE TITLE
1.3.1 ❌ 获取变量失败

### ISSUE THREAD

**Issue by miozus** [thqby/vscode-autohotkey2-lsp#88]
after update computer yesterday , i found that class method can not connect with each other, such as jump to method implement. 

Nomatter how i reinstall and reload vscode window.

my computer system version:

```bash
版本	Windows 10 教育版
版本号	21H2
安装日期	‎2022/‎4/‎17
操作系统内部版本	19044.1645
体验	Windows Feature Experience Pack 120.2212.4170
```

and vscode output log:

```bash
c:\Users\miozus\.vscode\extensions\thqby.vscode-autohotkey2-lsp-1.3.1\server\dist\server.js:1
(very long js file )

ReferenceError: Cannot access 'i' before initialization
    at c:\Users\miozus\.vscode\extensions\thqby.vscode-autohotkey2-lsp-1.3.1\server\dist\server.js:1:345419
    at t.runscript (c:\Users\miozus\.vscode\extensions\thqby.vscode-autohotkey2-lsp-1.3.1\server\dist\server.js:1:176360)
    at b (c:\Users\miozus\.vscode\extensions\thqby.vscode-autohotkey2-lsp-1.3.1\server\dist\server.js:1:344918)
    at async c:\Users\miozus\.vscode\extensions\thqby.vscode-autohotkey2-lsp-1.3.1\server\dist\server.js:1:339907
[Info  - 09:01:37] Connection to server got closed. Server will restart.
[Error - 09:01:37] Request textDocument/semanticTokens/full failed.
Error: Connection got disposed.
    at Object.dispose (c:\Users\miozus\.vscode\extensions\thqby.vscode-autohotkey2-lsp-1.3.1\client\dist\extension.js:1:35805)
    at Object.dispose (c:\Users\miozus\.vscode\extensions\thqby.vscode-autohotkey2-lsp-1.3.1\client\dist\extension.js:1:115896)
    at w.handleConnectionClosed (c:\Users\miozus\.vscode\extensions\thqby.vscode-autohotkey2-lsp-1.3.1\client\dist\extension.js:1:116109)
    at w.handleConnectionClosed (c:\Users\miozus\.vscode\extensions\thqby.vscode-autohotkey2-lsp-1.3.1\client\dist\extension.js:1:176473)
    at t (c:\Users\miozus\.vscode\extensions\thqby.vscode-autohotkey2-lsp-1.3.1\client\dist\extension.js:1:114198)
    at r.invoke (c:\Users\miozus\.vscode\extensions\thqby.vscode-autohotkey2-lsp-1.3.1\client\dist\extension.js:1:37418)
    at o.fire (c:\Users\miozus\.vscode\extensions\thqby.vscode-autohotkey2-lsp-1.3.1\client\dist\extension.js:1:38179)
    at Q (c:\Users\miozus\.vscode\extensions\thqby.vscode-autohotkey2-lsp-1.3.1\client\dist\extension.js:1:25063)
    at r.invoke (c:\Users\miozus\.vscode\extensions\thqby.vscode-autohotkey2-lsp-1.3.1\client\dist\extension.js:1:37418)
    at o.fire (c:\Users\miozus\.vscode\extensions\thqby.vscode-autohotkey2-lsp-1.3.1\client\dist\extension.js:1:38179)
    at d.fireClose (c:\Users\miozus\.vscode\extensions\thqby.vscode-autohotkey2-lsp-1.3.1\client\dist\extension.js:1:46060)
    at ChildProcess.<anonymous> (c:\Users\miozus\.vscode\extensions\thqby.vscode-autohotkey2-lsp-1.3.1\client\dist\extension.js:1:57026)
    at ChildProcess.emit (node:events:402:35)
    at maybeClose (node:internal/child_process:1064:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
```

**Comment by miozus** [comment]
resovle method 

before:

setting > autohotkey >  interpreter path:

```bash
D:\tools\AutoHotkey\AutoHotkey_H\AutoHotkey64.exe
```
after:

remove it (keep empty) and reload vscode window , everything is ok!

**Comment by miozus** [comment]
After I got a new laptop and reisntall this plugin ,and I met the question again ,so I went back to see my answer how to resolve.

**Comment by thqby** [comment]
也是这个错误？ `ReferenceError: Cannot access 'i' before initialization`
